version: "3.8"

services:

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /exposed-dir:/srv
      - /exposed-dir/filebrowser.db:/database.db
    ports:
      - 8080:80
    security_opt:
      - no-new-privileges:true