# This is based on a tutorial made by Techno Tim on youtube and his blog
# Blog post can be found below
# https://docs.technotim.live/posts/grafana-loki/

version: "3"

networks:
  loki:

services:

  loki:
    container_name: loki
    image: grafana/loki:2.4.0
    restart: always
    environment:
      GUID: 1000
      PGID: 1000
    volumes:
      - ${BASE_PATH}/loki:/etc/loki
    ports:
      - ${LOKI_PORT}:3100
    
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.0
    restart: always
    environment:
      GUID: 1000
      PGID: 1000
    volumes:
      - /var/log:/var/log
      - ${BASE_PATH}/promtail:/etc/promtail
    ports:
      - ${PROMTAIL_PORT}:1514
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    environment:
      GUID: 1000
      PGID: 1000
    volumes:
    - ${BASE_PATH}/grafana:/var/lib/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - loki