version: '3.6'
services:
  
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    environment:
      GITLAB_ROOT_EMAIL: ${ROOT_EMAIL}
      GITLAB_ROOT_PASSWORD: ${ROOT_PASSWD}
      external_url: ${PROTOCOL}://${HOSTNAME}
    ports:
      - ${HTTP_PORT}:80 # HTTP Port
      - ${HTTPS_PORT}:443 # HTTPS Port
      - ${SSH_PORT}:22 # SSH Port
    volumes:
      - ${BASE_PATH}/config:/etc/gitlab
      - ${BASE_PATH}/logs:/var/log/gitlab
      - ${BASE_PATH}/data:/var/opt/gitlab
    shm_size: 256m
    hostname: ${HOSTNAME}
