version: "3.8"

services:
  
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    networks:
      - mongodb_net
    ports:
      - ${DB_PORT}:2707
    volumes:
      - ${DATA_DIR}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    networks:
      - mongodb_net
    ports:
      - ${WEB_PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${WEB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${WEB_PASSWD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWD}@mongo:27017/

networks:
  mongodb_net: 